const mongoose = require("mongoose");

const loanApplicationSchema = new mongoose.Schema(
    {
        // Applicant who owns this loan application
        applicant: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "User",
            required: true,
            index: true
        },

        // Personal information
        personalDetails: {
            fullName: {
                type: String,
                trim: true,
                maxlength: 100
            },

            dateOfBirth: {
                type: Date
            },

            panNumber: {
                type: String,
                trim: true,
                uppercase: true
            },

            address: {
                type: String,
                trim: true,
                maxlength: 500
            }
        },

        // Loan information
        loanDetails: {
            loanType: {
                type: String,
                enum: ["PERSONAL", "HOME", "VEHICLE", "BUSINESS"]
            },

            amount: {
                type: Number,
                min: 1000
            },

            tenure: {
                type: Number,
                min: 1
            },

            purpose: {
                type: String,
                trim: true,
                maxlength: 500
            }
        },

        // Income information
        incomeDetails: {
            monthlyIncome: {
                type: Number,
                min: 0
            },

            employmentType: {
                type: String,
                enum: [
                    "SALARIED",
                    "SELF_EMPLOYED",
                    "BUSINESS_OWNER",
                    "OTHER"
                ]
            }
        },

        // Current application status
        status: {
            type: String,
            enum: [
                "DRAFT",
                "SUBMITTED",
                "UNDER_REVIEW",
                "MORE_INFO_NEEDED",
                "OFFICER_RECOMMENDED_APPROVAL",
                "OFFICER_RECOMMENDED_REJECTION",
                "APPROVED",
                "REJECTED"
            ],
            default: "DRAFT",
            index: true
        },

        // Sample annual interest rate assigned according to loan type
        interestRate: {
            type: Number,
            min: 0
        },

        // EMI preview/calculation
        estimatedEMI: {
            type: Number,
            min: 0
        },

        // Eligibility result generated by Loan Officer
        eligibilityResult: {
            checked: {
                type: Boolean,
                default: false
            },

            eligible: {
                type: Boolean,
                default: false
            },

            checks: [
                {
                    rule: {
                        type: String,
                        required: true
                    },

                    passed: {
                        type: Boolean,
                        required: true
                    },

                    message: {
                        type: String
                    }
                }
            ],

            checkedAt: {
                type: Date
            }
        },

        // Loan Officer review
        officerReview: {
            officer: {
                type: mongoose.Schema.Types.ObjectId,
                ref: "User"
            },

            recommendation: {
                type: String,
                enum: [
                    "APPROVAL",
                    "REJECTION",
                    "MORE_INFO"
                ]
            },

            note: {
                type: String,
                trim: true,
                maxlength: 1000
            },

            reviewedAt: {
                type: Date
            }
        },

        // Admin final decision
        adminReview: {
            admin: {
                type: mongoose.Schema.Types.ObjectId,
                ref: "User"
            },

            decision: {
                type: String,
                enum: [
                    "APPROVED",
                    "REJECTED"
                ]
            },

            remarks: {
                type: String,
                trim: true,
                maxlength: 1000
            },

            decidedAt: {
                type: Date
            }
        },

        // Tracks applicant responses to requests for more information
        additionalInfoRequests: [
            {
                note: {
                    type: String,
                    required: true,
                    trim: true,
                    maxlength: 1000
                },

                requestedBy: {
                    type: mongoose.Schema.Types.ObjectId,
                    ref: "User",
                    required: true
                },

                requestedAt: {
                    type: Date,
                    default: Date.now
                },

                respondedAt: {
                    type: Date
                }
            }
        ],

        submittedAt: {
            type: Date
        }
    },
    {
        timestamps: true
    }
);

// Useful for officer/admin list filtering and sorting
loanApplicationSchema.index({ status: 1, createdAt: -1 });
loanApplicationSchema.index({ "loanDetails.loanType": 1 });
loanApplicationSchema.index({ applicant: 1, createdAt: -1 });

module.exports = mongoose.model(
    "LoanApplication",
    loanApplicationSchema
);